[workspace]
members = ["contracts/*", "packages/*"]

exclude = ["contracts/outpost-sunrise-swap-external-axelar", "packages/strategy-evm"]

[profile.release]
rpath = false
lto = true
overflow-checks = true
opt-level = 3
debug = false
debug-assertions = false