[workspace]
members = ["contracts/*"]
exclude = ["contracts/outpost-sunrise-swap-external-axelar"]

[profile.release]
rpath = false
lto = true
overflow-checks = true
opt-level = 3
debug = false
debug-assertions = false