/**
 * This file was automatically generated by @cosmwasm/ts-codegen@0.35.3.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run the @cosmwasm/ts-codegen generate command to regenerate this file.
 */

export interface InstantiateMsg {
  authority: string;
}
export type ExecuteMsg =
  | {
      update_params: UpdateParamsMsg;
    }
  | {
      send_to_sunrise: SendToSunriseMsg;
    };
export interface UpdateParamsMsg {
  authority?: string | null;
}
export interface SendToSunriseMsg {
  channel_id: string;
  memo: string;
  sunrise_address: string;
}
export type QueryMsg = {
  params: {};
};
export type Addr = string;
export interface Params {
  authority: Addr;
}
