[package]
name = "strategy"
version = "1.0.0"
authors = []
edition = "2018"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# for quicker tests, cargo test --lib

[dependencies]
cosmwasm-std = { version = "2.1.0", features = ["stargate"] }
cosmwasm-schema = "2.1.0"